### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by MartialFouc** [knowbee/llvd#104]
Hi @knowbee,
I have download few course without any problem. But since yesterday, this message occurs after 1, 2 or 3 videos was download.
My connexion is perfect, no proxy, no VPN.
_`There is a connection error. Please check your connectivity.`_

Before the error message it start downloading the file, but the file is only a 0 bytes file.

It's the same with or without -t,
I'm on mac 11.7.3
Best

**Comment by knowbee** [comment]
Hi @michael-hart-github
Could you please provide me with the URL of the course you were trying to download? This information will help me to better understand the issue and find a solution.

**Comment by MartialFouc** [comment]
yes, that one : 
https://www.linkedin.com/learning/demystifying-audio-synthesis-beyond-the-basics/synth-programming-deep-dive?autoplay=true

And
https://www.linkedin.com/learning/demystifying-audio-synthesis-the-basics/learning-synthesis?autoplay=true

Thanks

**Comment by dimiric** [comment]
Thanks for reporting the issue @MartialFouc
I have also been experiencing this as well.  Seems to be occurring more frequently.  when it does happen, it creates a 0-size file and then breaks out of the course being worked on,  Doesn't advance, but if I run llvd again, it moves past the video and tries for the next.  Just happens that it keeps failing and generating the 0-size file.   Hope this helps.

![image](https://user-images.githubusercontent.com/41164643/220431305-62150761-1da4-4697-8474-740500a891b2.png)
![image](https://user-images.githubusercontent.com/41164643/220433178-f0efef5b-89a2-4de6-aa6b-267ee2b9c551.png)

**Comment by MartialFouc** [comment]
Exactly, it creates a 0-size file and stop the downloading process.
I need erase the last 0-size file, then restart llvd commande, it skips all already download files and start downloading.
I need to do that for each new video.

**Comment by dimiric** [comment]
Any thoughts on this one?  Is it possible to add some error checking so it'll retry the video?

I've written a script to cycle down through a list of learning paths, and just some things I've noticed:
- LinkedIn has an API limit.  Meaning once it thinks you've made enough calls to their site for the day, it seems to reject all new attempts until it resets that counter at midnight GMT.
- I have not been able to determine what that threshold is.
- I'm wondering if it considers every call part of that counter.  Meaning the initial "What courses are part of this Path?", and then "What videos are in this Course?", and then check each video link (before it checks if the video was already downloaded) maybe to ensure it is the right size?  My point is that when I download a path, and it dies with the 0-size file, and then I delete that file and restart it...  It seems like I'm definitely hitting that daily threshold after numerous restarts, despite not getting as many videos as when I wasn't getting the 0-size issue.
- Is it possible to set it up to download the list of courses and videos for a learning path into a filelist, and then only make calls for the missing videos?  I believe I've been able to grab the course list and included videos without actually being logged in, so maybe it can be done without impacting that daily threshold.
- Also, is there any way to grab the chapter quizzes?

Sorry for the long message, just trying to help.

**Comment by extraportal** [comment]
Same. Connection error after one video downloaded.

**Comment by maqboolkhan** [comment]
Also happening for me. 
And the thing is when i remove zero byte file and try again, it downloads the file but same error occurs for next video but when you repeat them same process it downloads that video and error happens again.
I tried with `-t` but did not help either.

**Comment by NonneTrapuE** [comment]
Have the same problem... Linkedin locked downloads ?

**Comment by knowbee** [comment]
#113
