### ISSUE TITLE
There is a connection error. Please check your connectivity.

### ISSUE THREAD

**Issue by RoDanny2021** [knowbee/llvd#105]
Hello,
Sorry for my poor English...
After some time, when downloading, appear "There is a connection error. Please check your connectivity." and stop download....
Last file is 0 bytes.... can make a change after restart downloading remove all file with 0 bytes and start download with first file with 0 bytes?

**Comment by onehex** [comment]
@knowbee  plz solve these issues

**Comment by knowbee** [comment]
@onehex I will fix this

**Comment by ashish2199** [comment]
Here is a small script i use to remove all the zero size files

`
#!/bin/bash

# Navigate to the directory where the files are located
cd <your folder path>

# Find all files with size of zero bytes and delete them
find . -depth -type f -size 0 -exec rm {} +
`

**Comment by maqboolkhan** [comment]
Also having the same issue

**Comment by manelgmail** [comment]
Just let me download one chapter and after that give me this error, you need to delete the error chapter with zero bytes and start the download again, I did that several times until I decided to connect trough VPN, since then they download all the course!

**Comment by knowbee** [comment]
#113
