### ISSUE TITLE
That course is not found

### ISSUE THREAD

**Issue by aoneahsan** [knowbee/llvd#108]
getting this error when trying to download a course.

That course is not found

**Comment by aoneahsan** [comment]
course url whose slug i'm using
https://www.linkedin.com/learning/aws-for-developers-identity-access-management-iam/aws-user-security-with-iam-15113020?autoplay=true


llvd -c “aws-for-developers-identity-access-management-iam”



llvd -c “aws-for-developers-identity-access-management-iam” --cookies

**Comment by picwellwisher12pk** [comment]
I guess our account is banned 😃

**Comment by knowbee** [comment]
<img width="1321" alt="Screenshot 2023-06-30 at 14 32 32" src="https://github.com/knowbee/llvd/assets/31471062/52f0b39d-0630-4324-b558-a487bea0600a">
This is an issue with your account, I will go ahead and close this
