### ISSUE TITLE
SyntaxWarning: invalid escape sequence

### ISSUE THREAD

**Issue by jaknz** [knowbee/llvd#121]
Running `Docker version 24.0.7, build afdd53b` and `docker run ghcr.io/knowbee/llvd:master -c "course name" -r 720` inside Debian on WSL, I get the following error output with an abort:

> $ docker run ghcr.io/knowbee/llvd:master -c "azure-devops-continuous-delivery-with-yaml-pipelines" -r 720
/usr/local/lib/python3.12/site-packages/llvd-3.0.7-py3.12.egg/llvd/app.py:251: SyntaxWarning: invalid escape sequence '\d'
/usr/local/lib/python3.12/site-packages/llvd-3.0.7-py3.12.egg/llvd/app.py:251: SyntaxWarning: invalid escape sequence '\d'
Please enter your Linkedin email address: Aborted!

Any idea how to progress past this? I'm operating fully inside the Debian VM, so no wierdness from Windows file paths or anything like that.

Same thing when I run help:
> $ docker run ghcr.io/knowbee/llvd:master --help
/usr/local/lib/python3.12/site-packages/llvd-3.0.7-py3.12.egg/llvd/app.py:251: SyntaxWarning: invalid escape sequence '\d'
/usr/local/lib/python3.12/site-packages/llvd-3.0.7-py3.12.egg/llvd/app.py:251: SyntaxWarning: invalid escape sequence '\d'
Usage: llvd [OPTIONS]
> 
>  Linkedin learning video downloader cli tool example: llvd --course
  "java-8-essential"
...

**Comment by knowbee** [comment]
@jaknz Thanks for reporting this issue. make sure you are running the latest docker image, it has been fixed in v3.0.8.
