### ISSUE TITLE
Note download path in readme.md

### ISSUE THREAD

**Issue by notparthreally** [knowbee/llvd#127]
It is very unclear where the downloaded course videos are stored. Please make adequate changes to the readme to inform the user where downloads are stored.

**Comment by knowbee** [comment]
@notparthreally Would you mind adding that for me as your first contribution?

**Comment by notparthreally** [comment]
Sure

**Comment by notparthreally** [comment]
Hey, would you be able to provide me download paths on Linux, mac and a docker system?
I currently only have a windows system running ... :)
