### ISSUE TITLE
Your internet connection is slow

### ISSUE THREAD

**Issue by neomrx** [knowbee/llvd#17]
Hi,

I still reviced the message "Your internet connection is slow", and con't download nothing.

ping www.linkedin.com -t

Envoi d’une requête 'ping' sur www.linkedin.com [13.107.42.14] avec 32 octets de données :
Réponse de 13.107.42.14 : octets=32 temps=49 ms TTL=116
Réponse de 13.107.42.14 : octets=32 temps=41 ms TTL=116
Réponse de 13.107.42.14 : octets=32 temps=44 ms TTL=116
Réponse de 13.107.42.14 : octets=32 temps=40 ms TTL=116
Réponse de 13.107.42.14 : octets=32 temps=39 ms TTL=116
Réponse de 13.107.42.14 : octets=32 temps=43 ms TTL=116
Réponse de 13.107.42.14 : octets=32 temps=56 ms TTL=116

please help.

**Comment by knowbee** [comment]
Is this happening on every course ? If not share me a link to the course you are trying to download and is failing,and see if i can debug

**Comment by neomrx** [comment]
yep, i try whith some courses and the result is the same, for example :
 https://www.linkedin.com/learning/transformation-digitale-avec-microsoft-365-les-ressources-humaines/recruter-efficacement?u=26104482

**Comment by knowbee** [comment]
Do you have a `linkedin learning premium account` ? You are probably trying to download courses that you don't have access to.
Try to download this free course( https://www.linkedin.com/learning/recovering-from-a-layoff/ ) and let me know if it fails too

**Comment by neomrx** [comment]
no, i dont have a learning premium account, it's a privilage given from my entreprise.
and yes your link work well.
hope some good news

**Comment by knowbee** [comment]
sorry to hear that...upgrade to the newest version with better error message

**Comment by neomrx** [comment]
thanks a lot for your time.
