### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by hostsistemas** [knowbee/llvd#19]
Don't download subtitles.
Please add option to download subtitles.
Thank you

**Comment by knowbee** [comment]
This feature has been added.
You can now use the `--caption` or `-ca` flag to download videos with subtitles

**Comment by hostsistemas** [comment]
Error: no such option: --caption

with -ca flag return this message: You must have a premium account to download this course

without -ca flag download works fine

**Comment by Giulidan** [comment]
Is there a way to just download subtitles? I downloaded courses without the captions option and don't want to download them all again just to add subtitles.
