### ISSUE TITLE
Ft:batch script for windows

### ISSUE THREAD

**Issue by knowbee** [knowbee/llvd#2]
For now, the installation script is for linux based systems. It would be great if `llvd` supported windows too

**Comment by silverhairs** [comment]
I think it would have been better to host it on PyPI, it'd have resolved this platform issue

**Comment by knowbee** [comment]
Can you make a PR ?

**Comment by knowbee** [comment]
> I think it would have been better to host it on PyPI, it'd have resolved this platform issue

Can you make a PR ?

**Comment by silverhairs** [comment]
Yeah, sure

**Comment by silverhairs** [comment]
> Yeah, sure
#3
