### ISSUE TITLE
subtitle

### ISSUE THREAD

**Issue by hostsistemas** [knowbee/llvd#21]
Error: no such option: --caption

with -ca flag return this message: You must have a premium account to download this course

without -ca flag download works fine

**Comment by knowbee** [comment]
can you share me the link of the course that you are trying to download?

**Comment by hostsistemas** [comment]
https://www.linkedin.com/learning/php-for-wordpress

**Comment by knowbee** [comment]
It works for me
![sreenshot1](https://user-images.githubusercontent.com/31471062/105632713-61c1ea80-5e5d-11eb-98bf-249a46260c0a.png)

- Please make sure you have the latest version of `llvd`. try `pip --no-cache-dir install llvd`
- Make sure you have a learning premium account

**Comment by hostsistemas** [comment]
![](https://raw.githubusercontent.com/hostsistemas/whatsapp-button/master/524.jpg)

**Comment by knowbee** [comment]
Interesting...I will try to debug on a windows machine and see why flags are failing. I will get back to you soon.

**Comment by knowbee** [comment]
This issue has been fixed

**Comment by hostsistemas** [comment]
Works fine now
