### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hostsistemas** [knowbee/llvd#23]
Returns this message several times:
     - You must have a premium account to download this course

And I need to restart the download again and again...

![image](https://user-images.githubusercontent.com/13827400/105930303-30494a80-6028-11eb-8088-6d60be3e8412.png)

![image](https://user-images.githubusercontent.com/13827400/105930322-363f2b80-6028-11eb-8334-096e101d5045.png)

![image](https://user-images.githubusercontent.com/13827400/105930330-3e976680-6028-11eb-8744-2b4f7b1be022.png)

**Comment by knowbee** [comment]
This issue has been fixed
check `llvd` version `2.0.1`

**Comment by hostsistemas** [comment]
I tested version 2.0.1 and it didn't solve the problem

**Comment by knowbee** [comment]
What is the error this time ?

**Comment by hostsistemas** [comment]
the same problem continues

**Comment by knowbee** [comment]
I want to see the screenshot..Are you using it behind a proxy?

**Comment by knowbee** [comment]
I want a screenshot because I am printing the error in the code to help me understand the real issue

**Comment by hostsistemas** [comment]
After starting the download;
download many videos but not all;
after downloading many videos;
Returns this message;
------- You must have a premium account to download this course
And I need to restart the download again and again...;
I can download all the videos but I have to restart (login)/resume download several times

**Comment by knowbee** [comment]
This type of error is not in the updated version `2.0.1`...Please uninstall `llvd` and reinstall again

**Comment by hostsistemas** [comment]
how to uninstall?

**Comment by knowbee** [comment]
pip uninstall `llvd`
if you get an error do so with powershell as an administrator.
To reinstall do `pip install llvd=='2.0.1'`

**Comment by hostsistemas** [comment]
![image](https://user-images.githubusercontent.com/13827400/106023752-dd15dd00-60a5-11eb-9f8e-852fc3b538f9.png)

**Comment by knowbee** [comment]
This error is valid because you have a poor internet connection...`requests` package maximum retries when are reached `llvd` stops
You might want to try again 

I am going to close this issue if there are no other issues.

**Comment by hostsistemas** [comment]
My Internet conection is 5M**b**/s (1.98M**B**/s)

**Comment by knowbee** [comment]
That is weird

**Comment by hostsistemas** [comment]
I am grateful for the script and for you to respond so quickly, but do not use the word "poor", perhaps your country may not offend, but in other countries it may offend a lot for having other meanings.

Have a nice day.
