### ISSUE TITLE
Cookie based authentication

### ISSUE THREAD

**Issue by Learnpython-code** [knowbee/llvd#27]
Thank you so much for your contribution in this project, it's help a lot, we can't stay connect all day, we need to work anytime in the courses, it's possible to download the courses with cookie based authentication. All the best.

**Comment by knowbee** [comment]
Your requested feature has been added,
Here is a short tutorial 
## Cookie-based authentication

- 1.  Click on the options in google chrome (top right with 3 vertical dots).
- 2.  After this, click on more tools followed by Developer Tools (you can also reach here by using the keyboard combination — ctrl+shift+I).

- 3.  Now once you’ve gained access to the developer tools, navigate to the Application tab, and copy the value of two cookies from there named li_at and JSESSIONID respectively.

- 3.  create a cookies.txt file to a place you want to download your courses then paste in the values of li_at and JSESSIONID as shown below.

#### Example (`cookies.txt`)

```sh
li_at=xxxxx
JSESSIONID="ajax:xxxxxx"
```

```cli

    $ llvd --help
    $ llvd -c "Course Title" -r 720 --cookies

```
