### ISSUE TITLE
Requests / bugs

### ISSUE THREAD

**Issue by jttttttttt** [knowbee/llvd#32]
Hi! Really liking this tool, thanks a lot for making it. Just a few observations:

1. It would be great if the topic folders would be numbered like in the content overview (for example> '1. Overview', '2. Subtopic X', etc.).

2. When exercise files are already in the folder, it will download them again. Maybe have the option to skip already downloaded files.

3. If a video has only been partially downloaded (maybe due to an error), it will skip it. I don't know if you have a good way to compare filesizes so that incomplete videos will be redownloaded.

4. I am downloading the course 'Deke's Techniques' and the ' in the course name threw n error. It tried a few things and it finally worked with 'Deke-s techniques'. 

Thanks!

**Comment by knowbee** [comment]
Nice catch....I will work on them in my free time

**Comment by joaofl** [comment]
Agreed with @jttttttttt . I also missed those features he mentioned. Apart from that, It works just fine, and It seems to be the only "linkedin downloader" around that currently works! Nice work.
I'll add the features I miss to this thread as well:  

5. Possibility of downloading multiple courses (maybe collections or saved lists?)

6. Have username and pass saved on config file to avoid re-typing

I will try to help on implementing some of these features.

To start from, @knowbee , what do you think of having a json config file to store some preferences? somethig like `~/.llvd-conf.json`
That could be used to store "encrypted" user and pass, cookies info, folder names format, download dir...
I could try to get that in place. Not sure with Windows and Mac though

**Comment by knowbee** [comment]
> config file to store some preference

I think it is a great idea, but we would have to make sure it is compatible across multiple platforms...Windows sometimes is unpredictable when you as a developer are only using Mac Os or Linux based OS

**Comment by knowbee** [comment]
Requested features can be found in this version 
`https://pypi.org/project/llvd/2.2.1/`
