### ISSUE TITLE
cant install 

### ISSUE THREAD

**Issue by shadowdragon007** [knowbee/llvd#33]
C:\Users\Dragoon\Downloads\Compressed\Wagakki Band - Vocalo Zanmai\llvd-master>$ pip --no-cache-dir install llvd
'$' is not recognized as an internal or external command,
operable program or batch file.

**Comment by shadowdragon007** [comment]
solved the last one. 
Where should i put the cookies file. Please provide a cookies file 
F:\New folder\1 Games\llvd-master>llvd -c "How to Motivate Yourself to Do What’s Most Important" -r 720 -ca
Do you want to login with cookies? [y/N]: y
cookies.txt not found or is empty

**Comment by knowbee** [comment]
> solved the last one.
> Where should i put the cookies file. Please provide a cookies file
> F:\New folder\1 Games\llvd-master>llvd -c "How to Motivate Yourself to Do What’s Most Important" -r 720 -ca
> Do you want to login with cookies? [y/N]: y
> cookies.txt not found or is empty

**Comment by knowbee** [comment]
You put your cookies.txt file in the folder you want to download a course...in your example you would put it in the llvd-master folder.

**Comment by knowbee** [comment]
Follow this guide on how to get cookies from your browser: https://github.com/knowbee/llvd#cookie-based-authentication
