### ISSUE TITLE
not downloading

### ISSUE THREAD

**Issue by shadowdragon007** [knowbee/llvd#34]
F:\New folder\1 Games\llvd-master>llvd -c "How to Motivate Yourself to Do What’s Most Important" -r 720 -ca
Do you want to login with cookies? [y/N]: y

'elements'
Poor network connection, try again .

i have 50 mbps connection. 

The cookies file only have these two line correct
JSESSIONID=
li_at=

**Comment by knowbee** [comment]
parsing apostrophe characters is the one causing the error. I will fix it very soon

**Comment by knowbee** [comment]
Try version `2.0.6` the issue is fixed 

https://pypi.org/project/llvd/2.0.6/
