### ISSUE TITLE
HTTPSConnectionPool(host='dms.licdn.com', port=443): Max retries exceeded with url

### ISSUE THREAD

**Issue by Boussarhane** [knowbee/llvd#36]
I started downloading some videos.... then I get this error  message 

HTTPSConnectionPool(host='dms.licdn.com', port=443): Max retries exceeded with url: /playlist/C4D0DAQFlJ5jiMxdvKQ/learning-original-video-vbr-720/0/1598841035324?e=1618750800&v=beta&t=mUNck_mtu2dc9dxNP-05lHD9U3aG9PpLY6cnlCvotZI (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026707A5B1C0>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))
Failed to connect, try again later

Any idea guys ? thank you

**Comment by knowbee** [comment]
Does it keep happening after retrying ? if so what course were you trying to download?

**Comment by Boussarhane** [comment]
I'm trying this course: L'essentiel de Spring Boot (It's in French)
And I tried it again now I ve got :

[Errno 22] Invalid argument: "l-essentiel-de-spring-boot/Introduction/1-Bienvenue dans « L'essentiel de Spring Boot\t».mp4"
Failed to connect, try again later

**Comment by knowbee** [comment]
Let me try to debug the problem, I will get back to you soon

**Comment by Boussarhane** [comment]
> Let me try to debug the problem, I will get back to you soon

Thank you.

**Comment by knowbee** [comment]
Try this version

https://pypi.org/project/llvd/2.0.7/

**Comment by knowbee** [comment]
Try this version and let me know

https://pypi.org/project/llvd/2.0.8/

**Comment by Boussarhane** [comment]
> Try this version and let me know
> 
> https://pypi.org/project/llvd/2.0.8/

I tried to install it by running: pip --no-cache-dir install llvd, but I got this error :


D:\>pip --no-cache-dir install llvd
Collecting llvd
  Downloading llvd-2.0.8.tar.gz (6.7 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mehdi\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-_2sdl35q\\llvd_56edff8732df445fbbe0224e6358b2a2\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-_2sdl35q\\llvd_56edff8732df445fbbe0224e6358b2a2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Mehdi\AppData\Local\Temp\pip-pip-egg-info-5uygr0w4'
         cwd: C:\Users\Mehdi\AppData\Local\Temp\pip-install-_2sdl35q\llvd_56edff8732df445fbbe0224e6358b2a2\
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/02/51/792a569040ecce0ecc5777ff0cfd0f9925d8497d1d7d7ab96f2c0e4085d9/llvd-2.0.8.tar.gz#sha256=be2c39db603ee1ed2e3082462e4faed9e6649ac7be297e15ac820a1e515533b5 (from https://pypi.org/simple/llvd/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading llvd-2.0.6.tar.gz (6.7 kB)

**Comment by Boussarhane** [comment]
> Try this version and let me know
> 
> https://pypi.org/project/llvd/2.0.8/

C:\Users\Mehdi>llvd -c "L'essentiel de Spring Boot" -r 720
Do you want to login with cookies? [y/N]: n
Please enter your Linkedin email address: ************@*****.com
Enter your Linkedin Password:
\

current: 1
format: 720p

Bienvenue dans « L'essentiel de Spring Boot     »

[Errno 22] Invalid argument: "l-essentiel-de-spring-boot/Introduction/1-Bienvenue dans « L'essentiel de Spring Boot\t».mp4"
Failed to connect, try again later

C:\Users\Mehdi>pip list
Package        Version
-------------- ---------
beautifulsoup4 4.9.3
certifi        2020.12.5
chardet        4.0.0
click          7.1.2
click-spinner  0.1.10
idna           2.10
llvd           2.0.8
pip            21.0.1
requests       2.25.1
setuptools     49.2.1
soupsieve      2.1
tqdm           4.55.0
urllib3        1.26.2

C:\Users\Mehdi>

**Comment by knowbee** [comment]
make sure you install the latest version with `pip3 install llvd=="2
![screenshot](https://user-images.githubusercontent.com/31471062/115117268-fab85b80-9f9d-11eb-91c3-2e69859bf53a.png)
.0.8"`

**Comment by Boussarhane** [comment]
I did it with pip3 but, the same issue:

C:\Users\Mehdi>**pip3 install llvd=="2.0.8"**
Requirement already satisfied: llvd==2.0.8 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (2.0.8)
Requirement already satisfied: beautifulsoup4==4.9.3 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (4.9.3)
Requirement already satisfied: certifi==2020.12.5 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (2020.12.5)
Requirement already satisfied: chardet==4.0.0 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (4.0.0)
Requirement already satisfied: click==7.1.2 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (7.1.2)
Requirement already satisfied: idna==2.10 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (2.10)
Requirement already satisfied: requests==2.25.1 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (2.25.1)
Requirement already satisfied: soupsieve==2.1 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (2.1)
Requirement already satisfied: tqdm==4.55.0 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (4.55.0)
Requirement already satisfied: urllib3==1.26.2 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (1.26.2)
Requirement already satisfied: click_spinner==0.1.10 in c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages (from llvd==2.0.8) (0.1.10)

C:\Users\Mehdi>**llvd -c "L'essentiel de Spring Boot" -r 720**
Do you want to login with cookies? [y/N]: n
Please enter your Linkedin email address: ***********@****.com
Enter your Linkedin Password:
/

current: 1
format: 720p

Bienvenue dans « L'essentiel de Spring Boot     »

[Errno 22] Invalid argument: "l-essentiel-de-spring-boot/Introduction/1-Bienvenue dans « L'essentiel de Spring Boot\t».mp4"
Failed to connect, try again later

C:\Users\Mehdi>

**Comment by knowbee** [comment]
Windows does not allow some characters in filenames unlike Linux or Mac Os. I have tried to fixed that.
Try this version and let me know
`https://pypi.org/project/llvd/2.0.9/`

**Comment by Boussarhane** [comment]
> Windows does not allow some characters in filenames unlike Linux or Mac Os. I have tried to fixed that.
> Try this version and let me know
> `https://pypi.org/project/llvd/2.0.9/`

It works for this one: **llvd -c "L'essentiel de Spring Boot" -r 720**. thank you.

But I tried two other courses and it doesn't work. find below the error for the other courses.

C:\Users\Mehdi>**llvd -c "L'essentiel d'ASP.NET Core pour .NET 5" -r 720**
Do you want to login with cookies? [y/N]: n
Please enter your Linkedin email address: ****************@*****.com
Enter your Linkedin Password:
/

'elements'
Failed to connect, try again later


C:\Users\Mehdi>**llvd -c "Python : L'analyse de données" -r 720**
Do you want to login with cookies? [y/N]: n
Please enter your Linkedin email address: ****************@*****.com
Enter your Linkedin Password:
|

'elements'
Failed to connect, try again later

C:\Users\Mehdi>

**Comment by knowbee** [comment]
Because of how impossible it is to take care of every senario, from now on you can copy the slug of the course from the url in linkedin learning platform then use it instead of course name

For eg:

`llvd -c "l-essentiel-d-asp-dot-net-core-pour-dot-net-5"` 
instead of 
llvd -c "L'essentiel d'ASP.NET Core pour .NET 5"

Slug can be found by navigating to the course.
I hope this helps.

![one](https://user-images.githubusercontent.com/31471062/115133418-5cadab00-a008-11eb-9b81-c531900f8e84.png)
![two](https://user-images.githubusercontent.com/31471062/115133419-5e776e80-a008-11eb-9c33-a518477dcde9.png)

**Comment by Boussarhane** [comment]
It works Now!! Thank you so much.

I know it's not easy to predict all cases but step by step your program will be complete.

**Comment by Boussarhane** [comment]
It works Now!! Thank you so much.

I know it's not easy to predict all cases but step by step your program will be complete.

And I think the only remaining (issue)  is to find a way to deal with **HTTPSConnectionPool(host='dms.licdn.com', port=443): Max retries exceeded with url:**
