### ISSUE TITLE
cont download entire videos, says need premium account

### ISSUE THREAD

**Issue by shadowdragon007** [knowbee/llvd#38]
hi, i am using account provide by my uni. is there a way in which the program first asks to login and then starts downloads

**Comment by knowbee** [comment]
You could use cookie based authentication

Login into the linkedin learning with the account provided by the University in the browser and grab the cookies and make sure you follow the exact steps explained on this section (`https://github.com/knowbee/llvd#cookie-based-authentication`)

**Comment by knowbee** [comment]
And if it says you need a premium account , you do need that. I am sorry

**Comment by shadowdragon007** [comment]
i did login through the uni account 
![Capture](https://user-images.githubusercontent.com/57890782/115343462-5168a400-a1ef-11eb-86bc-5a6033834787.JPG)
and created a cookie file and pasted that values there. is the i did it correct

**Comment by knowbee** [comment]
This is not an issue related to LLVD, the account provided by your UNI is not premium. So you need one if you are trying to download premium videos. I am going to close this issue.
