### ISSUE TITLE
Login via password error

### ISSUE THREAD

**Issue by capriciousduck** [knowbee/llvd#43]
Downloading courses via email and password doesn't work. I've rechecked using my credentials. Though, with cookies it works perfectly.

**Comment by knowbee** [comment]
Show me a screenshot of the error you see

**Comment by capriciousduck** [comment]
It only says "Wrong credentials". To check, I manually opened the site with same credentials and I logged in but not in llvd. It says wrong credentials.

**Comment by knowbee** [comment]
Have you tried to open a text editor and write your password, copy it and the paste it in the `llvd` password prompt ? Try that and let me know if the problem persist

**Comment by capriciousduck** [comment]
Still the problem persists.

**Comment by knowbee** [comment]
is your Two-step verification turned on ?

**Comment by capriciousduck** [comment]
No

**Comment by valenkovsky** [comment]
I can confirm that right credentials doesn't work anymore. It seems they have changed something in Linkedin authorization recently, because all Linkedin downloaders here on GitHub don't work anymore. The cookies way still works

**Comment by knowbee** [comment]
Well it is a good thing cookies way still works. I will try to see if there is a way to hack the password login.

**Comment by knowbee** [comment]
Well it is a good thing cookies way still works. I will try to see if there is a way to hack the password login.

**Comment by capriciousduck** [comment]
Ok

**Comment by knowbee** [comment]
I just tested on my device version 2.1.1 login with password works? What version are you currently running?

**Comment by capriciousduck** [comment]
latest one. Installed using `pip3 install llvd`

**Comment by knowbee** [comment]
so i am a bit confused here ..you opend two different issues... one saying you can not login another saying you can't install `llvd`?

**Comment by capriciousduck** [comment]
Oops. That must be a typo or something. Sorry.
