### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by capriciousduck** [knowbee/llvd#44]
I am getting the following error while installing with pip3.

`pip3 --no-cache-dir install llvd`

The error:

`Collecting llvd
  Downloading https://files.pythonhosted.org/packages/e2/f9/da6d3ef0cf382de3f3f55ddeb8585b97d108dd43b0e9ed2ad3f4c52ec3a9/llvd-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-603isxv1/llvd/setup.py", line 7, in <module>
        readme = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 631: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-603isxv1/llvd/`

**Comment by knowbee** [comment]
reinstall python 3 and make sure you install `llvd` as administrator

**Comment by capriciousduck** [comment]
Yes. I reinstalled. Still the same error. And I did run the llvd as administrator, even as root user.

**Comment by knowbee** [comment]
pip install llvd==2.2.1

close terminal (command line and reopen) then run run `llvd --help`

**Comment by knowbee** [comment]
> Yes. I reinstalled. Still the same error. And I did run the llvd as administrator, even as root user.

It is something about how python is setup on your computer not `llvd` related, sorry i couldn't help

**Comment by knowbee** [comment]
check to see if python3 site-packages is present in your PATH

**Comment by capriciousduck** [comment]
This is in my PATH

/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by knowbee** [comment]
You can see that python is not there...google how to add python to your path and fix that.

**Comment by capriciousduck** [comment]
Ok

**Comment by knowbee** [comment]
what is your currrent OS?

**Comment by capriciousduck** [comment]
Ubuntu 20.04

**Comment by capriciousduck** [comment]
What to append to my path?

**Comment by capriciousduck** [comment]
I'll try installing by cloning the repo.

**Comment by capriciousduck** [comment]
This either didn't work. Can you please tell me what to  add to the path so that I will append it?

**Comment by capriciousduck** [comment]
I got it installed now. But password auth is still not working.

**Comment by knowbee** [comment]
try cookies then....You have options
