### ISSUE TITLE
Exceeded 30 redirects.

### ISSUE THREAD

**Issue by Boussarhane** [knowbee/llvd#45]
When I try to download any course I get this error just after running : **llvd -c "course-url" -r 720**

$ llvd -c "programming-foundations-algorithms" -r 720
Do you want to login with cookies? [y/N]: y

Exceeded 30 redirects.
Failed to connect, try again later

**Comment by knowbee** [comment]
To login with cookies, add --cookies flag. and make sure you are using the latest version of ```llvd```
