### ISSUE TITLE
"This video is locked, you probably need a premium account", although I am logged in with a premium account

### ISSUE THREAD

**Issue by ohadhawk** [knowbee/llvd#54]
I am logged in with a premium account and able to view all course videos through the browser.
When I'm using the llvd I'm still getting "This video is locked, you probably need a premium account" for all the course chapters except for two. (intro and another one)
I tried both '--cookies' and username+pass, both give the same results.
Tried 360p, 540p and 720p, all give the same result.
Tried with and without captions, same result.
[log.txt](https://github.com/knowbee/llvd/files/6587465/log.txt)

**Comment by knowbee** [comment]
I have a premium account and i am able to download the course.. make sure you have `llvd 2.2.6` and try again
<img width="943" alt="logs" src="https://user-images.githubusercontent.com/31471062/120591722-eb517c80-c43c-11eb-8b4f-641315b26f25.png">

**Comment by ohadhawk** [comment]
I do:

![2021-06-03 09_13_57-Window](https://user-images.githubusercontent.com/1254388/120596291-3f179200-c44c-11eb-86ec-867a0c2e9465.png)

Any debug data I can supply ?

**Comment by knowbee** [comment]
Yeah you should be able to download them, not sure why you are getting that error, it has probably something to do with the fact that it is an organization account and urls might be different

**Comment by ohadhawk** [comment]
Is there any debug info I could provide so that such support be added ?
It's an amazing tool and will be a shame not to make use of it.

**Comment by knowbee** [comment]
Clone `llvd` locally and uninstall it from your computer, then navigate to app.py  where you will see this snippet `
except Exception as e:                        if 'url' in str(e):                            click.echo(                                click.style(f"This video is locked, you probably "\                                    f"need a premium account", fg="red"))` 

Print the exception then reinstall `llvd` like this: `python3 setup.py install`.(as admin)

Post here the exception
Thanks

**Comment by ohadhawk** [comment]
Thanks for that.
Followed the steps and for my best of understanding added the right prints, including the json itself.
Attaching the log as well as the file with my changes.
I hope you'll have some insights.
[log2.txt](https://github.com/knowbee/llvd/files/6603995/log2.txt)
[app.py.zip](https://github.com/knowbee/llvd/files/6603996/app.py.zip)

**Comment by knowbee** [comment]
What i got from this is that the account you are trying to use is not really premium..surely you can watch the videos on your Linkedin but the urls llvd use to download are hidden.

**Comment by knowbee** [comment]
You could try to create a free trial account and use that instead...you will notice that it is gonna work

**Comment by ohadhawk** [comment]
I understand. Thank you for the effort !
