### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by 0rg4nik** [knowbee/llvd#56]
This issue comes very frequently after every 3-4 videos. Then i have to manually go to the path and delete the zero-byte file on which the error occured and then have re-run from the command line. 
**int() argument must be a string, a bytes-like object or a number, not 'NoneType'**

**Comment by knowbee** [comment]
What version of `llvd` are you using ?

**Comment by 0rg4nik** [comment]
version 2.1.1

**Comment by knowbee** [comment]
this issue was fixed by #50 .. make sure you install the latest version of `llvd` current version is llvd 2.2.6

**Comment by 0rg4nik** [comment]
Thanks, issue resolved after updating to the latest version 2.2.6.
