### ISSUE TITLE
Video quality resolutions issues

### ISSUE THREAD

**Issue by Ledigh** [knowbee/llvd#57]
Good Morning!
Firstly, thanks for the program, your time, your efforts:
Very helpful tool :)

I’ve encountered issues concerning video quality resolutions. By default it’s 720p, but using, for example, this following link: [Advanced Drum Recording Session with Josh Freese](https://www.linkedin.com/learning/advanced-drum-recording-session-with-josh-freese?u=76279468)
…the results are a mix of 540p and 720p, though all 540p still have their corresponding 720p versions available; I can even download them from the “Internet Download Manager” button through its browser extension.

I’ve also tried with another downloader [LinkedIn Learning Courses Downloader](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader) Same results!
Any ideas on how to fix it ?
Thanks ;)

**Comment by knowbee** [comment]
Does it happen only when you are trying to download this course ?
