### ISSUE TITLE
Learning path download request

### ISSUE THREAD

**Issue by greenpeer** [knowbee/llvd#59]
Hi, it's a great tool to download videos, but could you add the learning path download function? thank you.

**Comment by knowbee** [comment]
That would be a good feature, something i will surely consider working on once i get time.

Thanks for using the tool.

**Comment by mhmdNoman** [comment]
Hello @knowbee Thank you for making this tool. it's really great tool. i see you have some enhancement(sorting sections numerically) this is awesome before it i had to organize them manually.
I'm using this tool for like last 3 moths or so, friend of mine introduced me to this. before i was using youtube-dl.

as you said if got some time and opportunity please do consider implementing path downloading functionality. no rush though.
what you created already it's really helping me.
thank you again. :)

**Comment by m0bileDev** [comment]
Yeah I needed this functionality too so I opened PR #70. Once approved we should be able to close this issue.
