### ISSUE TITLE
Requirement Already Satisfied

### ISSUE THREAD

**Issue by girron** [knowbee/llvd#60]
After running the install command for llvd I receive:

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: llvd in ./Library/Python/3.8/lib/python/site-packages (2.2.6)
Requirement already satisfied: beautifulsoup4==4.9.3 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (4.9.3)
Requirement already satisfied: tqdm==4.55.0 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (4.55.0)
Requirement already satisfied: click-spinner==0.1.10 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (0.1.10)
Requirement already satisfied: idna==2.10 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (2.10)
Requirement already satisfied: click==7.1.2 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (7.1.2)
Requirement already satisfied: urllib3==1.26.2 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (1.26.2)
Requirement already satisfied: chardet==4.0.0 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (4.0.0)
Requirement already satisfied: requests==2.25.1 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (2.25.1)
Requirement already satisfied: certifi==2020.12.5 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (2020.12.5)
Requirement already satisfied: soupsieve==2.1 in ./Library/Python/3.8/lib/python/site-packages (from llvd) (2.1)

**Comment by knowbee** [comment]
What is the issued ?
