### ISSUE TITLE
Not letting download video from slug

### ISSUE THREAD

**Issue by kunaldas926** [knowbee/llvd#62]
Not letting download video from many slugs including but not limited to: [`learning-django-2`](https://www.linkedin.com/learning/learning-django-2), [`java-11-plus-essential-training`](https://www.linkedin.com/learning/java-11-plus-essential-training/).
`llvd -c "java-11-plus-essential-training" -r 720 --caption --cookies` and `llvd -c "javalearning-django-2" -r 720 --caption --cookies` throws `This video is locked, you probably need a premium account`.
I already have a premium subscription.

**Comment by knowbee** [comment]
No sure if you really have a premium account, because as you can tell by my screenshot i was able to download the same course
<img width="965" alt="Screen Shot 2021-09-06 at 18 30 44" src="https://user-images.githubusercontent.com/31471062/132245019-9231531f-a561-4328-bb77-4734fad29cc5.png">

**Comment by knowbee** [comment]
You probably have a limited account
