### ISSUE TITLE
cannot download, "video is locked" error

### ISSUE THREAD

**Issue by shawn8888** [knowbee/llvd#65]
couse slug:
onenote-2016-essential-training
llvd can only download the first video of the chapter, and all others gives need premium account error.

Please help!

**Comment by knowbee** [comment]
You need a premium account for such course. Usually the intro video is free to download

**Comment by knowbee** [comment]
I have a premium account and i am able to download all videos

<img width="1383" alt="Screen Shot 2021-10-15 at 16 40 48" src="https://user-images.githubusercontent.com/31471062/137505783-b12f3720-ddb8-4377-b664-ff6c316b0a58.png">

**Comment by shawn8888** [comment]
So, my account can only view the course but not able to download? 
I thought llvd could act as a browser to download the video...
