### ISSUE TITLE
Download multiple courses / learning paths

### ISSUE THREAD

**Issue by SkourtsidisGiorgos** [knowbee/llvd#67]
I want to define learning paths or multiple videos in a file and download them in one go.
Ex
{ "link1",
  "link2",
... etc
}

or 
{ "learning_path1",
  "learning_path2",
...
etc
}

It is possible?

**Comment by m0bileDev** [comment]
@SkourtsidisGiorgos  with PR #70, once you specify the token from learning path it will download all courses. Does not load from file though.

For example:
https://www.linkedin.com/learning/paths/advance-your-skills-in-python-8969631

the token is "advance-your-skills-in-python-8969631"

See "--help" for more details.
