### ISSUE TITLE
Can't download video using a corporate account.

### ISSUE THREAD

**Issue by ddemydenko** [knowbee/llvd#69]
I am using a corporate account, and I can access the paid content in the browser, but I can't download it with llvd.

**Comment by nk13gr** [comment]
Same for me, I am using a corporate account, and I can access the paid content in the browser.  When I tried downloading a course with llvd (using cookie authentication), some videos were downloaded, but for the rest of the course videos I got the message "This video is locked, you probably need a premium account".  How can this happen?  If it were for my subscription status, it should allow or block all of them, not some of them.  It doesn't make sense to me.  Any thoughts on this...?

**Comment by ddemydenko** [comment]
@knowbee Thanks for the answer, the auth using cookie doesn't work. I mean, it works in sense - it allows me to login, but llvd probably can't recognize that I am using a corporate account. My assumption is to add extra cookies support. There are a lot of values for LinkedIn, honestly, I don't know which one needs to add. Mabe it worst to add all of them.
![image](https://user-images.githubusercontent.com/32139284/145571283-9f4a5e02-13c3-4547-9d9e-15dd983afd9d.png)

**Comment by nk13gr** [comment]
@knowbee I came across another post of yours at https://githubmemory.com/repo/knowbee/llvd/issues/54, saying "You could try to create a free trial account and use that instead...you will notice that it is gonna work", and I can confirm it does work with a free trial account.  Really nice work!

**Comment by ddemydenko** [comment]
@nk13gr I have tried downloading with youtube-dl. The same error, so I suspect Linkedin somehow keeps tracking user activity. It is most likely impossible to load video with a corporate account, at least make it in a simple way.

**Comment by theazlan89** [comment]
> @knowbee Thanks for the answer, the auth using cookie doesn't work. I mean, it works in sense - it allows me to login, but llvd probably can't recognize that I am using a corporate account. My assumption is to add extra cookies support. There are a lot of values for LinkedIn, honestly, I don't know which one needs to add. Maybe it is worth adding all of them. ![image](https://user-images.githubusercontent.com/32139284/145571283-9f4a5e02-13c3-4547-9d9e-15dd983afd9d.png)

is this worked?
