### ISSUE TITLE
No module named llvd.__main__; 'llvd' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by hi2rashid** [knowbee/llvd#82]
For me this worked

`llvd -c "learning-data-analytics-1-foundations" --cookies -r 720
`
However.

Issue in windows 10 and 11 and debian.

Command i am executing is

python3 -m llvd -c "learning-data-analytics-1-foundations" --cookies -r 720

I have installed python3, pip3 and llvd

![image](https://user-images.githubusercontent.com/10250923/169224244-a893bca5-56b4-45d7-9744-aa1ebcb4c2b3.png)

Looks like __main.py__ file is missing in the module? may be it needs to be defined [__main.py__ sample](https://github.com/tox-dev/tox/blob/master/src/tox/__main__.py)
![image](https://user-images.githubusercontent.com/10250923/169224763-410bd4ee-0208-46ed-af8f-15029246980b.png)

**Comment by Rockycodex** [comment]
Same issue I'm facing while using on Mac

**Comment by knowbee** [comment]
This is issue is gonna be closed. We have added an alternative to run LLVD with docker. This will solve a lot of issues regarding os compatibility.

**Comment by m4heshd** [comment]
@knowbee Docker is great but doing releases with standalone executables would be way better.
