### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by neoOpus** [knowbee/llvd#86]
llvd 3.0.1 requires click==7.1.2, but you have click 8.1.3 which is incompatible.
llvd 3.0.1 requires requests==2.25.1, but you have requests 2.28.1 which is incompatible.
llvd 3.0.1 requires soupsieve==2.1, but you have soupsieve 2.3.2.post1 which is incompatible.
llvd 3.0.1 requires tqdm==4.55.0, but you have tqdm 4.64.0 which is incompatible.
llvd 3.0.1 requires urllib3==1.26.2, but you have urllib3 1.26.10 which is incompatible.

**Comment by knowbee** [comment]
Thanks
