### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by zaytiri** [knowbee/llvd#88]
Hi,
I'm currently using version 3.0.1 and every 1-2 videos this error occurs.
I've already seen other old issues on this but even with the fix you did, it still throws an error on line 31 as seen as below:

![Screenshot_1](https://user-images.githubusercontent.com/64491586/188840657-395727e4-a0d7-4272-a5d4-cfef8179b761.png)
Thanks!

**Comment by knowbee** [comment]
Could you please send me a link to the course where this occurred?

**Comment by zaytiri** [comment]
Yes!

Every course from this path:
https://www.linkedin.com/learning/paths/improve-your-drawing-skills

And most of the courses from this path:
https://www.linkedin.com/learning/paths/prepare-for-the-google-associate-android-developer-certification

But, the error also happened to me very randomly, although not frequently, on any course I was downloading, so maybe it's not something especific to these courses? But it happened mostly on these.

**Comment by knowbee** [comment]
Thank you; I'll look into it and come up with a solution.

**Comment by knowbee** [comment]
I was not able to see the problem my self, I will close this issue
