### ISSUE TITLE
Unable to access container created by github action

### ISSUE THREAD

**Issue by andrew-su** [knowbee/llvd#89]
You need to update your visibility settings for other users to access the created container image.

See: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images and https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

**Comment by knowbee** [comment]
I have made it accessible to public. Can you confirm that it is working now ?

**Comment by andrew-su** [comment]
Perfect, it works now.

Closing the issue.
