### ISSUE TITLE
I'm having trouble downloading a very large course

### ISSUE THREAD

**Issue by FlorianGeorgiev** [knowbee/llvd#96]
LinkedIn Learning keeps banning me no mater how loose timings I put for throttling.
The course is very large and maybe this is the reason.
Everytime it bans me on a different video. The looser timings I put, the more videos it downloads.
This is the first error (a bunch of others follows):
Traceback (most recent call last):
  File "C:\python\lib\site-packages\llvd\app.py", line 221, in download_entire_course
    download_video(download_url, video_index, video_name, chapter_path, delay)
  File "C:\python\lib\site-packages\llvd\downloader.py", line 31, in download_video
    total=int(download_size),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

I think the error occurs in the moment they ban me.

My command line is: llvd -c "the-practicing-photographer" -ca -t 780,1020 --cookies

When I run again the command, when it looks if the video is downloaded, it doesn't use the trothling timings and maybe this leads to a ban from LinkedIn. If this is the reason, it will be useful if we could put more tight timings (I mean - different) only between two checks if a video is already downloaded. With another command line variable.

Thanks.

**Comment by knowbee** [comment]
This has been fixed in the most recent version; please let me know if you encounter this error again.

**Comment by FlorianGeorgiev** [comment]
I thought my version is the latest one. Came here and couldn’t figure out which version is the latest one. I’m new to gtihub and don’t understand its mechanism. Came here only to download it. I believe my version is 3.0.1, if I remember. Anyways, my subscription ended, so I can’t give any feedback. :(

**Comment by knowbee** [comment]
Latest version is 3.0.2
